# Generated by Django 4.1.1 on 2023-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
