# Generated by Django 4.1.1 on 2023-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='generatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
