# Generated by Django 4.1.1 on 2023-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_alter_otp_generatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='generatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
